import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Cursor from "./components/Cursor";
import NameHeader from "./components/NameHeader";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import { ThemeProvider } from "next-themes";
import ThemeChanger from "./components/ThemeChanger";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="cursor-none">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased duration-500 `}
      >

        <ThemeProvider>
          <Cursor />
          <ThemeChanger />
          <NameHeader />
          <Navigation />

          {children}

          <Footer />
        </ThemeProvider>

      </body>
    </html>
  );
}
